import { CityParams, District, DistrictId, ScenarioKey, ScenarioPreset } from "@/types/city";

export const districts: readonly District[] = [
  {
    id: "downtown",
    name: "Downtown + Rainey",
    q: 0,
    r: 0,
    baseLoadMW: 140,
    baseCapacityMW: 170,
    population: 65000,
    evAdoption: 0.32,
    solarPenetration: 0.18,
    criticality: 0.55,
    sensitivity: { heat: 1.25, storm: 1.1, event: 1.4 },
  },
  {
    id: "industrial",
    name: "East Industry + Airport",
    q: 1,
    r: 0,
    baseLoadMW: 165,
    baseCapacityMW: 190,
    population: 25000,
    evAdoption: 0.18,
    solarPenetration: 0.12,
    criticality: 0.35,
    sensitivity: { heat: 1.1, storm: 1.15, event: 1.05 },
  },
  {
    id: "university",
    name: "UT + West Campus",
    q: 0,
    r: 1,
    baseLoadMW: 105,
    baseCapacityMW: 140,
    population: 42000,
    evAdoption: 0.28,
    solarPenetration: 0.22,
    criticality: 0.3,
    sensitivity: { heat: 1.15, storm: 1.05, event: 1.2 },
  },
  {
    id: "medical",
    name: "Medical + Dell Seton",
    q: -1,
    r: 1,
    baseLoadMW: 120,
    baseCapacityMW: 155,
    population: 30000,
    evAdoption: 0.22,
    solarPenetration: 0.16,
    criticality: 0.95,
    sensitivity: { heat: 1.2, storm: 1.08, event: 1.1 },
  },
  {
    id: "eastside",
    name: "East Austin",
    q: -1,
    r: 0,
    baseLoadMW: 95,
    baseCapacityMW: 125,
    population: 52000,
    evAdoption: 0.3,
    solarPenetration: 0.2,
    criticality: 0.4,
    sensitivity: { heat: 1.3, storm: 1.05, event: 1.0 },
  },
  {
    id: "north",
    name: "North Burnet + Domain",
    q: 0,
    r: -1,
    baseLoadMW: 88,
    baseCapacityMW: 130,
    population: 60000,
    evAdoption: 0.38,
    solarPenetration: 0.26,
    criticality: 0.25,
    sensitivity: { heat: 1.18, storm: 1.02, event: 0.95 },
  },
  {
    id: "south",
    name: "South Lamar + SoCo",
    q: 1,
    r: -1,
    baseLoadMW: 92,
    baseCapacityMW: 128,
    population: 57000,
    evAdoption: 0.34,
    solarPenetration: 0.24,
    criticality: 0.3,
    sensitivity: { heat: 1.22, storm: 1.03, event: 1.0 },
  },
  {
    id: "waterfront",
    name: "Riverside + Lady Bird",
    q: -2,
    r: 1,
    baseLoadMW: 78,
    baseCapacityMW: 118,
    population: 24000,
    evAdoption: 0.26,
    solarPenetration: 0.28,
    criticality: 0.45,
    sensitivity: { heat: 1.12, storm: 1.35, event: 1.05 },
  },
] as const;

export const edges: readonly (readonly [DistrictId, DistrictId])[] = [
  ["downtown", "industrial"],
  ["downtown", "university"],
  ["downtown", "eastside"],
  ["university", "medical"],
  ["medical", "eastside"],
  ["eastside", "waterfront"],
  ["downtown", "north"],
  ["north", "south"],
  ["south", "industrial"],
] as const;

export const scenarios = {
  baseline: {
    name: "Baseline",
    params: {
      evAdoptionDelta: 0.0,
      solarDelta: 0.0,
      storageMWh: 0.0,
      microgridEnabled: false,
      demandResponseEnabled: false,
      heatwaveEnabled: false,
      stormEnabled: false,
      eventEnabled: false,
      criticalPriorityEnabled: true,
    },
  },
  heatwaveEvSurge: {
    name: "Heatwave + EV Surge",
    params: {
      evAdoptionDelta: 0.18,
      solarDelta: 0.0,
      storageMWh: 0.0,
      microgridEnabled: false,
      demandResponseEnabled: false,
      heatwaveEnabled: true,
      stormEnabled: false,
      eventEnabled: true,
      criticalPriorityEnabled: true,
    },
  },
  stormStress: {
    name: "Storm Stress",
    params: {
      evAdoptionDelta: 0.05,
      solarDelta: -0.05,
      storageMWh: 0.0,
      microgridEnabled: false,
      demandResponseEnabled: false,
      heatwaveEnabled: false,
      stormEnabled: true,
      eventEnabled: false,
      criticalPriorityEnabled: true,
    },
  },
  greenUpgrade: {
    name: "Green Upgrade",
    params: {
      evAdoptionDelta: 0.1,
      solarDelta: 0.18,
      storageMWh: 3.0,
      microgridEnabled: true,
      demandResponseEnabled: true,
      heatwaveEnabled: false,
      stormEnabled: false,
      eventEnabled: false,
      criticalPriorityEnabled: true,
    },
  },
} as const satisfies Record<ScenarioKey, ScenarioPreset>;

export const defaultParams: CityParams = {
  ...scenarios.baseline.params,
  budgetM: 5,
};
